# Generated by Django 5.1.3 on 2024-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='calorias',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='carbohidratos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='grasas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='proteinas',
            field=models.FloatField(default=0),
        ),
    ]
