# Generated by Django 5.1.3 on 2024-11-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0003_ingrediente_categoria_alter_ingrediente_calorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='calorias',
            field=models.FloatField(help_text='Calorías por cada 100 gramos'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='carbohidratos',
            field=models.FloatField(help_text='Carbohidratos (g) por cada 100 gramos'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='grasas',
            field=models.FloatField(help_text='Grasas (g) por cada 100 gramos'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='proteinas',
            field=models.FloatField(help_text='Proteínas (g) por cada 100 gramos'),
        ),
    ]
