"""Crear tabla stock

Revision ID: 31cc7ff5a18a
Revises: ec25bf191d0e
Create Date: 2025-05-24 05:35:06.896402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cc7ff5a18a'
down_revision = 'ec25bf191d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table(
        'stock',
        sa.Column('id_stock', sa.Integer(), primary_key=True),
        sa.Column('producto', sa.String(length=255), nullable=False, unique=True),
        sa.Column('cantidad_total', sa.Numeric(12, 2), nullable=False, server_default='0'),
        sa.Column('fecha_registro', sa.DateTime(), nullable=False,
                  server_default=sa.func.now()),
    )
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
