"""Tablas para generar ventas

Revision ID: 3ee40d20367b
Revises: 4463d86d4a61
Create Date: 2025-06-11 04:20:40.472873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee40d20367b'
down_revision = '4463d86d4a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('forma_pago', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('abono', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('kilos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_stock'], ['stock.id_stock'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('pagos_venta',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nro_documento', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_venta')
    op.drop_table('detalle_venta')
    op.drop_table('ventas')
    # ### end Alembic commands ###
