"""Crear tablas presupuesto_items y presupuesto_subitems

Revision ID: ec25bf191d0e
Revises: 2be5495a6288
Create Date: 2025-05-22 00:53:59.168267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec25bf191d0e'
down_revision = '2be5495a6288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presupuesto_items',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('presupuesto_subitems',
    sa.Column('id_subitem', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['presupuesto_items.id_item'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_subitem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presupuesto_subitems')
    op.drop_table('presupuesto_items')
    # ### end Alembic commands ###
