# Generated by Django 5.1.3 on 2024-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
