# Generated by Django 5.1.3 on 2024-11-30 00:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_tipo'),
        ('recetas_guardadas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetaguardada',
            unique_together={('usuario', 'receta')},
        ),
    ]
