# Generated by Django 5.1.3 on 2024-11-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0002_ingrediente_calorias_ingrediente_carbohidratos_and_more'),
        ('receta_ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('tiempo_preparacion', models.PositiveIntegerField()),
                ('tiempo_coccion', models.PositiveIntegerField()),
                ('porciones', models.PositiveIntegerField(default=1)),
                ('popularidad', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ingredientes', models.ManyToManyField(related_name='recetas', through='receta_ingrediente.RecetaIngrediente', to='ingredientes.ingrediente')),
            ],
        ),
    ]
