# Generated by Django 5.1.3 on 2024-11-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaalimentaria',
            name='categorias_no_aptas',
            field=models.ManyToManyField(blank=True, related_name='preferencias', to='categorias.categoria'),
        ),
    ]
