# Generated by Django 5.1.3 on 2024-11-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0002_ingrediente_calorias_ingrediente_carbohidratos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(default='gramos', max_length=50)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_recetas', to='ingredientes.ingrediente')),
            ],
        ),
    ]
