# Generated by Django 5.1.3 on 2024-11-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receta_ingrediente', '0001_initial'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetaingrediente',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_ingredientes', to='recetas.receta'),
        ),
    ]
