# Generated by Django 5.1.3 on 2024-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta_ingrediente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='unidad',
            field=models.CharField(choices=[('gramos', 'Gramos'), ('kilogramos', 'Kilogramos'), ('mililitros', 'Mililitros'), ('litros', 'Litros'), ('rebanadas', 'Rebanadas'), ('piezas', 'Piezas'), ('tazas', 'Tazas'), ('cucharadas', 'Cucharadas'), ('cucharaditas', 'Cucharaditas')], default='gramos', max_length=50),
        ),
    ]
